#!/bin/bash

set -e

if [ "$1" = "configure" ]; then
    for user in nova cinder glance keystone neutron
    do
        if ! getent group $user > /dev/null 2>&1; then
            addgroup --system $user >/dev/null
        fi

        if ! getent passwd $user > /dev/null 2>&1; then
            adduser --system --home /var/lib/$user --ingroup $user --no-create-home --shell /bin/false $user
        fi

        if [ "$(id -gn $user)"  = "nogroup" ]; then
          usermod -g $user $user
        fi
    done
fi

#DEBHELPER#
